runtime: python37

automatic_scaling:
  max_concurrent_requests: 40
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 1

handlers:
- url: /favicon.ico
  static_files: static/img/favicon/favicon.ico
  upload: static/img/favicon/favicon.ico
- url: /images
  static_dir: static/img
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /.*
  script: auto
